services:
  database:
    image: postgres:latest
    container_name: postgres-fortu
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keys:
    image: redis:7.4.2-alpine
    container_name: redis-fortu
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: